---
apiVersion: v1
kind: Secret
metadata:
 name: myserverworkload.mydevns.tap
stringData:
 values.yaml: |
   ---
   # workload_name: myserverworkload
   # replicas: 2
   # hostname: myserverworkload.mydevns.tap.mycompany.com
