apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: myserver-source-url.mydevns.tap.20230713040700.0.0+build.5155d72
spec:
  refName: myserver-source-url.mydevns.tap
  version: 20230713040700.0.0+build.5155d72
  releaseNotes: |
    Release v20230713040700.0.0+build.5155d72 of package myserver-source-url.mydevns.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: gcr.io/daisy-284300/pradnya/myserver-source-url-mydevns-bundle@sha256:fbd228649e4356b6d96c38cf9163b7e54e9df44e93c1f3b40c775b75a3e26d58
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        replicas:
          title: Replicas
          type: integer
          description: Number of replicas.
          default: 21

