---
apiVersion: v1
kind: Secret
metadata:
 name: myweb-img-to-url.mydevns.tap
stringData:
 values.yaml: |
   ---
    workload_name: myweb-img-to-url
    replicas: 10
    hostname: myweb-img-to-url.mydevns.tap.mycompany.com
